name:           IntervalIntMap
version:        '0.0.0.0'
synopsis:       Interval map
category:       Domain Specific Language
author:         Luis Pedro Coelho
maintainer:     luis@luispedro.org
license:        MIT
license-file:   COPYING
github:         luispedro/interval-to-int
default-extensions:
  - BangPatterns
  - OverloadedStrings
  - LambdaCase
  - TupleSections
  - CPP
dependencies:
  - base
  - containers
  - data-default
  - deepseq >=1.3
  - either
  - errors >=2.1
  - extra >=1.4
  - exceptions
  - MissingH >=1.3
  - network
  - parsec >=3.1
  - primitive >=0.6
  - process >=1.2.3
  - regex
  - safe
  - strict
  - resourcet >=1.1
  - tar >=0.5
  - text >=1.2
  - transformers
  - unliftio-core
  - unliftio
  - vector >=0.11
  - vector-algorithms

extra-source-files:
 - README.md
 - ChangeLog
ghc-options:
  - -Wall
  - -Wcompat
  - -fwarn-tabs
  - -fno-warn-missing-signatures
  - -O2

library:
    source-dirs: ./
    exposed-modules:
      - Data.IntervalIntMap.IntervalIntMap
    other-modules: []

tests:
  interval-int-map-test:
    source-dirs:
        - .
        - ./tests
    main: Tests.hs
    cpp-options: -DIS_BUILDING_TEST
    dependencies:
      - tasty
      - tasty-th
      - tasty-hunit
      - tasty-hedgehog
      - tasty-quickcheck
      - hedgehog
