name:           IntervalIntMap
version:        '0.0.0.0'
synopsis:       Interval map
category:       Domain Specific Language
author:         Luis Pedro Coelho
maintainer:     luis@luispedro.org
license:        MIT
license-file:   COPYING
github:         luispedro/interval-to-int
default-extensions:
  - BangPatterns
  - OverloadedStrings
  - LambdaCase
  - TupleSections
  - CPP
dependencies:
  - base
  - containers
  - deepseq
  - either
  - primitive
  - vector
  - vector-algorithms

extra-source-files:
 - README.md
 - ChangeLog
ghc-options:
  - -Wall
  - -Wcompat
  - -fwarn-tabs
  - -fno-warn-missing-signatures
  - -O2

library:
    source-dirs: ./
    exposed-modules:
      - Data.IntervalIntMap
    other-modules:
      - Data.IntervalIntMap.Internal.GrowableVector
      - Data.IntervalIntMap.Internal.IntervalIntIntMap

tests:
  interval-int-map-test:
    source-dirs:
        - .
        - ./tests
    main: Tests.hs
    cpp-options: -DIS_BUILDING_TEST
    dependencies:
      - tasty
      - tasty-th
      - tasty-hunit
      - tasty-hedgehog
      - tasty-quickcheck
      - hedgehog
